#!/bin/bash

# This script runs ci/build.sh in a Docker container.
#
# Usage:
#
#   build-in-docker NAME [ARGUMENTS]
#
# NAME: Sudirectory name in the dockerfiles directory.
# ARGUMENTS: Arguments that will be passed to ci/build.sh.

set -eu

name=${1}
shift

tag="ccache-build:$name-1"

# Build (if not exists):
docker build -t "$tag" "dockerfiles/$name"

# Cache compilation across docker sessions
mkdir -p build-in-docker
mkdir -p build-in-docker/docker-ccache

docker run --rm \
  --volume "$PWD:/source" \
  --volume "$PWD/build-in-docker/docker-ccache:/ccache" \
  --tmpfs /builddir:rw,exec \
  --workdir /builddir \
  --env CC="${CC:-}" \
  --env CFLAGS="${CFLAGS:-}" \
  --env CXX="${CXX:-}" \
  --env CXXFLAGS="${CXXFLAGS:-}" \
  --env LDFLAGS="${LDFLAGS:-}" \
  --env ASAN_OPTIONS="${ASAN_OPTIONS:-}" \
  --env CCACHE_LOC="/source" \
  --env SPECIAL="${SPECIAL:-}" \
  --env SCAN_BUILD="${SCAN_BUILD:-}" \
  --env CMAKE_PARAMS="${CMAKE_PARAMS:-}" \
  --env BUILDEXTRAFLAGS="${BUILDEXTRAFLAGS:-}" \
  --env NO_TEST="${NO_TEST:-}" \
  --env CCACHE_DIR=/ccache \
  "$tag" \
  /source/ci/build.sh "$@"
