#!/bin/sh

# This will compress (or recompress) the ccache cache directory,
# using the fast compression method (level 1) available with gzip.

CCACHE=${CCACHE:-ccache}
CCACHE_DIR=${CCACHE_DIR:-$HOME/.ccache}

# Set RECOMPRESS=true to do a recompress of less compressed files.
# Set DECOMPRESS=true to reverse the process and decompress cache.

RECOMPRESS=${RECOMPRESS:-false}
DECOMPRESS=${DECOMPRESS:-false}

VERBOSE=${VERBOSE:-false}
LEVEL=${LEVEL:-1}

# check for required programs, they should be present in the $PATH
if ! file --version >/dev/null; then echo "missing file"; exit 1; fi
if ! gzip --version >/dev/null; then echo "missing gzip"; exit 1; fi

# use parallel gzip (pigz) program for compression, if it's available
if pigz --version >/dev/null 2>&1; then pigz=pigz; else pigz=gzip; fi

find $CCACHE_DIR -mindepth 2 -type f | grep -v $CCACHE_DIR/tmp |
grep -v CACHEDIR.TAG | grep -v stats | grep -v manifest |
while read file; do
  magic=`file $file`
  if ! $DECOMPRESS && echo "$magic" | grep -v "compressed data" >/dev/null; then
    ! $VERBOSE || echo "Compressing $file"
    $pigz -n -$LEVEL <$file >$file.$$ && mv $file.$$ $file
  elif $DECOMPRESS && echo "$magic" | grep "compressed data" >/dev/null; then
    ! $VERBOSE || echo "Decompressing $file"
    gzip -d <$file >$file.$$ && mv $file.$$ $file
  elif $DECOMPRESS; then
    continue
  elif $RECOMPRESS && echo "$magic" | grep -v "max compression" >/dev/null; then
    ! $VERBOSE || echo "Recompressing $file"
    gzip -d <$file | $pigz -n -9 >$file.$$ && mv $file.$$ $file
  fi
done
