prefix = /usr/local

all:
	@echo "Available make targets:"
	@echo
	@echo "  install [prefix=...] [DESTDIR=...]"
	@echo
	@echo "Default prefix: $(prefix)"

install:
	./install.sh --prefix="$(prefix)" --destdir="$(DESTDIR)"
