FROM fedora:40

RUN dnf install -y \
        blake3-devel \
        ccache \
        clang \
        cmake \
        cpp-httplib-devel \
        diffutils \
        doctest-devel \
        elfutils \
        expected-devel \
        findutils \
        fmt-devel \
        gcc \
        gcc-c++ \
        hiredis-devel \
        less \
        libzstd-devel \
        ninja-build \
        perl \
        python3 \
        redis \
        xxhash-devel \
 && dnf clean all
