FROM alpine:latest

RUN apk add --no-cache \
                gcc libc-dev \
                make \
                bash \
                asciidoc \
                autoconf \
                zstd-dev \
        ##
