ccache news
===========

ccache 4.0
----------
Unreleased

High-level summary of changes (work in progress)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Compilation results are now stored in single aggregated files; before up to
  seven files per cached result were used.

- Result and manifest files are now compressed by the real-time compression
  algorithm Zstandard by default.

- BLAKE2b is now used instead of MD4 for hashing input.

- Added checksumming of result files using XXH64 to detect data corruption.

- Made the hard link mode less error prone.

- Added opt-in support for using file cloning (on Btrfs/XFS/APFS) to copy data
  to and from the cache.

- A C++11 compiler is now required to build ccache.

- Added a `-x/--show-compression` option which shows some statistics about
  cache compression.

- Added a `-X/--recompress` option which can be used to recompress the cache
  data with another compression level (or make it uncompressed). If you choose
  to disable compression by default or to use a level with a low compression
  ratio, you can recompress the cache with a higher compression level after the
  build or at another time when there are more CPU cycles available, for
  instance every night.

- A progress bar has been added to show the progress of time-consuming options
  like `-c/--cleanup`, `-C/--clear`, `-x/--show-compression` and
  `-X/--recompress`.

- When supported by the CPU, a SIMD-friendly (using AVX2) algorithm is now used
  to scan input source code for `__DATE__` and `__TIME__` macros. This can
  decrease the number of CPU cycles for a direct cache hit with up to 15% in
  some cases.

- (More to be written.)


ccache 3.7.9
------------
Release date: 2020-03-29

Bug fixes
~~~~~~~~~

- Fixed replacing of /dev/null when building as root with hard link mode
  enabled and using `-o /dev/null`.

- Removed incorrect assertion resulting in “ccache: error: Internal error in
  format” when using `-fdebug-prefix-map=X=` with X equal to `$PWD`.


Other
~~~~~

- Improved CUDA/NVCC support: Recognize `-dc` and `-x cu` options.

- Improved name of temporary file used in NFS-safe unlink.


ccache 3.7.8
------------
Release date: 2020-03-16

Bug fixes
~~~~~~~~~

- Use `$PWD` instead of the real CWD (current working directory) when checking
  for CWD in preprocessed output. This fixes a problem when `$PWD` includes a
  symlink part and the user has set `hash_dir = false`.

- Rewrote the Windows version of the lockfile routines. This should mitigate
  several problems with the old implementation.

- If `localtime_r` fails the epoch time is now logged instead of garbage.


Other
~~~~~

- Improved error message when a boolean environment variable has an invalid
  value.

- Improved the regression fix in ccache 3.7.5 related to not passing
  compilation-only options to the preprocessor.

- ccache’s PCH test suite now skips running the tests if it detects broken PCH
  compiler support.

- Fixed unit test failure on Windows.

- Fixed “stringop-truncation” build warning on Windows.

- Improved “x_rename” implementation on Windows.

- Improved removal of temporary file when rewriting absolute paths to relative
  in the dependency file.

- Clarified “include_file_ctime sloppiness” in the Performance section in the
  manual.


ccache 3.7.7
------------
Release date: 2020-01-05

Bug fixes
~~~~~~~~~

- Fixed a bug related to object file location in the dependency file (if using
  `-MD` or `-MMD` but not `-MF` and the build directory is not the same as the
  source directory then the object file location in the `.d` file would become
  incorrect). This fixes regression in ccache 3.7.5 introduced by the bug fix
  related to EDG-based compilers. Note that this removes support for EDG-based
  compilers again. (A better fix for this is planned for ccache 4.0.)

- Removed the unify mode since it has bugs and shortcomings that are non-trivial
  or impossible to fix: it doesn’t work with the direct mode, it doesn’t handle
  C++ raw strings correctly, it can give false cache hits for `.incbin`
  directives, it’s turned off when using `-g` and it can make line numbers in
  warning messages and `__LINE__` macros incorrect.

- mtime and ctime values are now stored in the manifest files only when
  sloppy_file_stat is set. This avoids adding superfluous manifest file entries
  on direct mode cache misses.

- A “Result:” line is now always printed to the log.

- The “cache miss” statistics counter will now be updated for read-only cache
  misses, making it consistent with the cache hit case.


ccache 3.7.6
------------
Release date: 2019-11-17

Bug fixes
~~~~~~~~~

- The opt-in “file_macro sloppiness” mode has been removed so that the input
  file path now is always included in the direct mode hash. This fixes a bug
  that could result in false cache hits in an edge case when “file_macro
  sloppiness” is enabled and several identical source files include a relative
  header file with the same name but in different directories.

- Statistics files are no longer lost when the filesystem of the cache is full.

- Bail out on too hard Clang option `-MJarg` (in addition to the previous
  bailout of `-MJ arg`).

- Properly handle color diagnostics in the depend mode as well.


ccache 3.7.5
------------
Release date: 2019-10-22

New features
~~~~~~~~~~~~

- Added support for `-MF=arg` (with an extra equal sign) as understood by
  EDG-based compilers.


Bug fixes
~~~~~~~~~

- Fixed a regression in 3.7.2 that could result in a warning message instead of
  an error in an edge case related to usage of “-Werror”.

- An implicit `-MQ` is now passed to the preprocessor only if the object file
  extension is non-standard. This will make it easier to use EDG-based
  compilers (e.g. GHS) which don’t understand `-MQ`. (This is a bug fix of the
  corresponding improvement implemented in ccache 3.4.)

- ccache now falls back to running the real compiler instead of failing fataly
  if an internal temporary file is missing after compilation.

- Fixed a crash if localtime returns null pointer in localtime_r replacement.

- Fixed header file dependency tracking when building ccache itself.

- Fixed warning during configure in out-of-tree build in developer mode.


ccache 3.7.4
------------
Release date: 2019-09-12

Improvements
~~~~~~~~~~~~

- Added support for the `-gz[=type]` compiler option (previously ccache would
  think that “-gz” alone would enable debug information, thus potentially
  including the current directory in the hash).

- Added support for converting paths like “/c/users/...” into relative paths on
  Windows.


ccache 3.7.3
------------
Release date: 2019-08-17

Bug fixes
~~~~~~~~~

- The cache size (which is counted in “used disk blocks”) is now correct on
  filesystems that use more or less disk blocks than conventional filesystems,
  e.g. ecryptfs or btrfs/zfs with transparent compression. This also fixes a
  related problem with ccache's own test suite when run on such file systems.

- Fixed a regression in 3.7.2 when using the compiler option “-Werror” and then
  “-Wno-error” later on the command line.


ccache 3.7.2
------------
Release date: 2019-07-19

Bug fixes
~~~~~~~~~

- The compiler option `-gdwarf*` no longer forces “run_second_cpp = true”.

- Added verification that the value passed to the `-o/--set-config` option is
  valid.

- Fixed detection of precompiled headers in the depend mode.

- Bail out on too hard Clang option `-ftime-trace`.

- ccache now updates the correct stats file when adding/updating manifest
  files. This bug previously made the file and size statistics counters
  incorrect over time.

- Fixed warnings from Clang about unused arguments during preprocessing.

- Unknown manifest versions are now handled gracefully in `--dump-manifest`.

- Fixed `make check` with “funny” locales.


Documentation
~~~~~~~~~~~~~

- Added a hint about not running `autogen.sh` when building from a release
  archive.

- Mention that `xsltproc` is needed when building from the source repository.


ccache 3.7.1
------------
Release date: 2019-05-01

Changes
~~~~~~~

- Fixed a problem when using the compiler option `-MF /dev/null`.

- Long commandlines are now handled gracefully on Windows by using the `@file`
  syntax to avoid hitting the commandline size limit.

- Fixed complaint from GCC 9’s `-Werror=format-overflow` when compiling ccache
  itself.


ccache 3.7
----------
Release date: 2019-04-23

Changes
~~~~~~~

- Fixed crash when the debug mode is enabled and the output file is in a
  non-writable directory, e.g. when the output file is `/dev/null`.

- Fixed an issue when printing very large log messages to the debug log.

- Fixed bugs related to support for `-gsplit-dwarf`. Previously ccache could
  produce an incorrect link to the `.dwo` file in the `.o` file.

- Compilations with /dev/null as the input file are now cached.

- ccache has learned how to construct the object filename if no `-o` option is
  given and the source filename does not include a `.` or ends with a `.`.

- Fixed a temporary file leak when the depend mode is enabled and the compiler
  produces standard error output.

- Fixed a bug in the depend mode where a manifest hash only could be associated
  with one set of header dependencies.

- Manifest files did not get marked as used on direct cache hits, so the LRU
  cache cleanup would incorrectly remove them eventually. This has been fixed.

- The rewriting of absolute paths into relative paths in the dependency file
  has been enabled in the depend mode as well.

- ccache now ignores unknown keys in configuration files for forward
  compatibility.

- Rearranged command-line options into sections in the help text.

- Documented the previously undocumented `--dump-manifest` and `--hash-file`
  options (only useful for debugging ccache itself).

- Added missing documentation for the command-line option `-k/--get-config`
  added in ccache 3.5.

- Renamed the `--print-config` command to `--show-config`.

- Added a new `--print-stats` command that prints statistics counters in
  machine-parsable (tab-separated) format.

- ccache no longer creates a missing output directory, thus mimicking the
  compiler behavior for `-o out/obj.o` when “out” doesn’t exist.

- `-fdebug-prefix-map=ARG`, `-ffile-prefix-map=ARG` and
  `-fmacro-prefix-map=ARG` are now included in the hash, but only the part
  before “ARG”. This fixes a bug where compiler feature detection of said flags
  would not work correctly with ccache.

- Bail out on too hard compiler option `-gtoggle`.

- Bail out on too hard Clang options `--analyze` and `-analyze`.

- Improved debug logging of file hashes in depend mode.

- Improved handling of various `-g*` options. In particular, ccache now
  understands that `-g0` cancels out previous `-g* options`.

- Worked around a problem with Automake related to `.d` files when using the
  hard link mode.

- Added opt-in (at configure time) support for enabling trace logs for
  profiling ccache itself. See `doc/DEVELOPER.md` in the code tree for more
  information

- Removed support for Fortran 77 again. Some Fortran support was added in
  ccache 3.3, but the implementation did not work when Fortran modules are
  involved.


ccache 3.6
----------
Release date: 2019-01-14

Changes
~~~~~~~

- ccache now has an opt-in “depend mode”. When enabled, ccache never executes
  the preprocessor, which results in much lower cache miss overhead at the
  expense of a lower potential cache hit rate. The depend mode is only possible
  to use when the compiler option `-MD` or `-MMD` is used.

- Added support for GCC’s `-ffile-prefix-map` option. The `-fmacro-prefix-map`
  option is now also skipped from the hash.

- Added support for multiple `-fsanitize-blacklist` arguments.

- ccache now includes the environment variables `LANG`, `LC_ALL`, `LC_CTYPE`
  and `LC_MESSAGES` in the hash since they may affect localization of compiler
  warning messages. Set sloppiness to `locale` to opt out of this.

- Fixed a problem due to Clang overwriting the output file when compiling an
  assembler file.

- Clarified the manual to explain the reasoning behind the “file_macro”
  sloppiness setting in a better way.

- ccache now handles several levels of nonexistent directories when rewriting
  absolute paths to relative.

- A new sloppiness setting `clang_index_store` makes ccache skip the Clang
  compiler option `-index-store-path` and its argument when computing the
  manifest hash. This is useful if you use Xcode, which uses an index store
  path derived from the local project path. Note that the index store won’t be
  updated correctly on cache hits if you enable this option.

- Rename sloppiness `no_system_headers` to `system_headers` for consistency
  with other options. `no_system_headers` can still be used as an
  (undocumented) alias.

- The GCC variables “DEPENDENCIES_OUTPUT” and “SUNPRO_DEPENDENCIES” are now
  supported correctly.

- The algorithm that scans for `__DATE_` and `__TIME__` tokens in the hashed
  source code now doesn’t produce false positives for tokens where `__DATE__`
  or `__TIME__` is a substring.


ccache 3.5.1
------------
Release date: 2019-01-02

Changes
~~~~~~~

- Added missing getopt_long.c source file to release archive.

- Fixed (harmless) compiler warnings when building ccache object files.

- CFLAGS is no longer passed to the linker when linking ccache.

- Improved development mode build flags.


ccache 3.5
----------
Release date: 2018-10-15

Changes
~~~~~~~

- Added a boolean `debug` (`CCACHE_DEBUG`) configuration option. When enabled,
  ccache will create per-object debug files that are helpful e.g. when
  debugging unexpected cache misses. See also the new “Cache debugging” section
  in the manual.

- Renamed `CCACHE_CC` to `CCACHE_COMPILER` (keeping the former as a deprecated
  alias).

- Added a new command-line option `-k/--get-config` that prints the value of a
  config key.

- It is now possible to let ccache hash a precomputed checksum file instead of
  the full content of a precompiled header. This can save time for large
  precompiled headers. Note that the build system needs to keep the checksum
  file in sync with the precompiled header for this to work.

- Improved performance substantially when using `hash_dir = false` on platforms
  like macOS where `getcwd()` is slow.

- Added “stats updated” timestamp in `ccache -s` output. This can be useful if
  you wonder whether ccache actually was used for your last build.

- Renamed “stats zero time” to “stats zeroed” and documented it. The counter is
  also now only present in `ccache -s` output when `ccache -z` actually has
  been called.

- The content of the `-fsanitize-blacklist` file is now included in the hash,
  so updates to the file will now correctly result in separate cache entries.

- It’s now possible to opt out of building and installing man pages when
  running `make install` in the source repository.

- If the compiler type can’t be detected (e.g. if it is named `cc`), use safer
  defaults that won’t trip up Clang.

- Made the ccache test suite work on FreeBSD.

- Added `file_stat_matches_ctime` option to disable ctime check if
  `file_stat_matches` is enabled.

- Made “./configure --without-bundled-zlib” do what’s intended.


ccache 3.4.3
-----------
Release date: 2018-09-02

Bug fixes
~~~~~~~~~

- Fixed a race condition when creating the initial config file in the cache
  directory.

- Bail out on too hard Clang option `-MJ`.

- Bail out on too hard option `-save-temps=obj`.

- Handle separate parameter to Clang option `-target` correctly.

- Upgraded bundled zlib to version 1.2.11.


ccache 3.4.2
------------
Release date: 2018-03-25

Bug fixes
~~~~~~~~~

- The cleanup algorithm has been fixed to not misbehave when files are removed
  by another process while the cleanup process is running. Previously, too many
  files could be removed from the cache if multiple cleanup processes were
  triggered at the same time, in extreme cases trimming the cache to a much
  smaller size than the configured limits.

- Correctly hash preprocessed headers located in a “.gch directory”.
  Previously, ccache would not pick up changes to such precompiled headers,
  risking false positive cache hits.

- Fixed build failure when using the bundled zlib sources.

- ccache 3.3.5 added a workaround for not triggering Clang errors when a
  precompiled header’s dependency has an updated timestamp (but identical
  content). That workaround is now only applied when the compiler is Clang.

- Made it possible to perform out-of-source builds in dev mode again.


ccache 3.4.1
------------
Release date: 2018-02-11

Bug fixes
~~~~~~~~~

- Fixed printing of version number in `ccache --version`.


ccache 3.4
----------
Release date: 2018-02-11

New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- The compiler option form `--sysroot arg` is now handled like the documented
  `--sysroot=arg` form.

- Added support for caching `.su` files generated by GCC flag `-fstack-usage`.

- ccache should now work with distcc’s “pump” wrapper.

- The optional unifier is no longer disabled when the direct mode is enabled.

- Added support for NVCC compiler options `--compiler-bindir/-ccbin`,
  `--output-directory/-odir` and `--libdevice-directory/-ldir`.

- Boolean environment variable settings no longer accept the following
  (case-insensitive) values: `0`, `false`, `disable` and `no`. All other values
  are accepted and taken to mean “true”. This is to stop users from setting
  e.g. `CCACHE_DISABLE=0` and then expect the cache to be used.

- Improved support for `run_second_cpp = false`: If combined with passing
  `-fdirectives-only` (GCC) or `frewrite-includes` (Clang) to the compiler,
  diagnostics warnings and similar will be correct.

- An implicit `-MQ` is now passed to the preprocessor only if the object file
  extension is non-standard. This should make it easier to use EDG-based
  compilers (e.g. GHS) which don’t understand `-MQ`.

- ccache now treats an unreadable configuration file just like a missing
  configuration file.

- Documented more pitfalls with enabling `hard_links` (`CCACHE_HARDLINK`).

- Documented caveats related to colored warnings from compilers.


Bug fixes
~~~~~~~~~

- File size and number counters are now updated correctly when files are
  overwritten in the cache, e.g. when using `CCACHE_RECACHE`.

- `run_second_cpp` is now forced for NVCC.

- Fixed how the NVCC options `-optf` and `-odir` are handled.


ccache 3.3.6
------------
Release date: 2018-01-28

New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Improved instructions on how to get cache hits between different working
  directories.


Bug fixes
~~~~~~~~~

- Fixed regression in ccache 3.3.5 related to the `UNCACHED_ERR_FD` feature.


ccache 3.3.5
------------
Release date: 2018-01-13


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Documented how automatic cache cleanup works.


Bug fixes
~~~~~~~~~

- Fixed a regression where the original order of debug options could be lost.
  This reverts the “Improved parsing of `-g*` options” feature in ccache 3.3.

- Multiple `-fdebug-prefix-map` options should now be handled correctly.

- Fixed matching of directories in the `ignore_headers_in_manifest`
  configuration option.

- Fixed detection of missing argument to `-opt`/`--options-file`.

- ccache now bails out when building a precompiled header if any of the
  corresponding header files has an updated timestamp. This fixes complaints
  from Clang.

- Fixed a bug related to erroneously storing a dependency file with absolute
  paths in the cache on a preprocessed hit.

- `ccache -c/--cleanup` now works like documented: it just recalculates size
  counters and trims the cache to not exceed the max size and file number
  limits. Previously, the forced cleanup took “limit_multiple” into account, so
  that `ccache -c/--cleanup` by default would trim the cache to 80% of the max
  limit.

- ccache no longer ignores linker arguments for Clang since Clang warns about
  them.

- Plugged a couple of file descriptor leaks.

- Fixed a bug where ccache would skip hashing the compiler argument following a
  `-fno-working-directory`, `-fworking-directory`, `-nostdinc`, `-nostdinc++`,
  `-remap` or `-trigraphs` option in preprocessor mode.


ccache 3.3.4
------------
Release date: 2017-02-17

New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Documented the different cache statistics counters.


Bug fixes
~~~~~~~~~

- Fixed a regression in ccache 3.3 related to potentially bad content of
  dependency files when compiling identical source code but with different
  source paths. This was only partially fixed in 3.3.2 and reverts the new
  “Names of included files are no longer included in the hash of the compiler’s
  preprocessed output” feature in 3.3.

- Corrected statistics counter for `-optf`/`--options-file` failure.

- Fixed undefined behavior warnings in ccache found by `-fsanitize=undefined`.

ccache 3.3.3
------------
Release date: 2016-10-26

Bug fixes
~~~~~~~~~

- ccache now detects usage of `.incbin` assembler directives in the source code
  and avoids caching such compilations.


ccache 3.3.2
------------
Release date: 2016-09-28

Bug fixes
~~~~~~~~~

- Fixed a regression in ccache 3.3 related to potentially bad content of
  dependency files when compiling identical source code but with different
  source paths.

- Fixed a regression in ccache 3.3.1: ccache could get confused when using the
  compiler option `-Wp,` to pass multiple options to the preprocessor,
  resulting in missing dependency files from direct mode cache hits.


ccache 3.3.1
------------
Release date: 2016-09-07

Bug fixes
~~~~~~~~~

- Fixed a problem in the “multiple `-arch` options” support introduced in 3.3.
  When using the direct mode (the default), different combinations of `-arch`
  options were not detected properly.

- Fixed an issue when compiler option `-Wp,-MT,path` is used instead of `-MT
  path` (and similar for `-MF`, `-MP` and `-MQ`) and `run_second_cpp`
  (`CCACHE_CPP2`) is enabled.


ccache 3.3
----------
Release date: 2016-08-27

Notes
~~~~~

- A C99-compatible compiler is now required to build ccache.


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- The configuration option `run_second_cpp` (`CCACHE_CPP2`) now defaults to
  true. This improves ccache’s out-of-the-box experience for compilers that
  can’t compile their own preprocessed output with the same outcome as if they
  compiled the real source code directly, e.g. newer versions of GCC and Clang.

- The configuration option `hash_dir` (`CCACHE_HASHDIR`) now defaults to true.

- Added a new `ignore_headers_in_manifest` configuration option, which
  specifies headers that should be ignored in the direct mode.

- Added a new `prefix_command_cpp` (`CCACHE_PREFIX_CPP`) configuration option,
  which specifies one or several prefixes to add to the command line ccache
  uses when invoking the preprocessor.

- Added a new `limit_multiple` (`CCACHE_LIMIT_MULTIPLE`) configuration option,
  which specifies how much of the cache to remove when cleaning.

- Added a new `keep_comments_cpp` (`CCACHE_COMMENTS`) configuration option,
  which tells ccache not to discard the comments before hashing preprocessor
  output. This can be used to check documentation with `-Wdocumentation`.

- Added a new sloppiness option `no_system_headers`, which tells ccache not to
  include system headers in manifest files.

- Added a new statistics counter that tracks the number of performed cleanups
  due to the cache size being over the limit. The value is shown in the output
  of “ccache -s”.

- Added support for relocating debug info directory using `-fdebug-prefix-map`.
  This allows for cache hits even when `hash_dir` is used in combination with
  `base_dir`.

- Added a new “cache hit rate” field to the output of “ccache -s”.

- Added support for caching compilation of assembler code produced by e.g. “gcc
  -S file.c”.

- Added support for cuda including the -optf/--options-file option.

- Added support for Fortran 77.

- Added support for multiple `-arch` options to produce "fat binaries".

- Multiple identical `-arch` arguments are now handled without bailing.

- The concatenated form of some long compiler options is now recognized, for
  example when using `-isystemPATH` instead of `-isystem PATH`.

- If hard-linking is enabled and but fails (e.g. due to cross-device linking),
  ccache now falls back to copying instead of running the compiler.

- Made the `hash_dir` option only have effect when generating debug info.

- ccache now knows how to convert absolute paths to relative paths inside
  dependency files when using `base_dir`.

- Improved parsing of `-g*` options.

- Made ccache understand `-Wp,-D*` options.

- ccache now understands the undocumented `-coverage` (only one dash) GCC
  option.

- Names of included files are no longer included in the hash of the compiler’s
  preprocessed output. This leads to more potential cache hits when not using
  the direct mode.

- Increased buffer size used when reading file data. This improves performance
  slightly.


Bug fixes
~~~~~~~~~

- Bail out on too hard compiler option `-P`.

- Fixed Clang test suite when running on Linux.

- Fixed build and test for MinGW32 and Windows.


ccache 3.2.9
------------
Release date: 2016-09-28

Bug fixes
~~~~~~~~~

- Fixed a regression in ccache 3.2.8: ccache could get confused when using the
  compiler option `-Wp,` to pass multiple options to the preprocessor,
  resulting in missing dependency files from direct mode cache hits.


ccache 3.2.8
------------
Release date: 2016-09-07

Bug fixes
~~~~~~~~~

- Fixed an issue when compiler option `-Wp,-MT,path` is used instead of `-MT
  path` (and similar for `-MF`, `-MP` and `-MQ`) and `run_second_cpp`
  (`CCACHE_CPP2`) is enabled.

- ccache now understands the undocumented `-coverage` (only one dash) GCC
  option.


ccache 3.2.7
------------
Release date: 2016-07-20

Bug fixes
~~~~~~~~~

- Fixed a bug which could lead to false cache hits for compiler command lines
  with a missing argument to an option that takes an argument.

- ccache now knows how to work around a glitch in the output of GCC 6’s
  preprocessor.


ccache 3.2.6
------------
Release date: 2016-07-12

Bug fixes
~~~~~~~~~

- Fixed build problem on QNX, which lacks “SA_RESTART”.

- Bail out on compiler option `-fstack-usage` since it creates a `.su` file
  which ccache currently doesn’t handle.

- Fixed a bug where (due to ccache rewriting paths) the compiler could choose
  incorrect include files if `CCACHE_BASEDIR` is used and the source file path
  is absolute and is a symlink.


ccache 3.2.5
------------
Release date: 2016-04-17


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Only pass Clang-specific `-stdlib=` to the preprocessor.

- Improved handling of stale NFS handles.

- Made it harder to misinterpret documentation of boolean environment settings’
  semantics.


Bug fixes
~~~~~~~~~

- Include m4 files used by configure.ac in the source dist archives.

- Corrected "Performance" section in the manual regarding `__DATE_`, `__TIME__`
  and `__FILE__` macros.

- Fixed build on Solaris 10+ and AIX 7.

- Fixed failure to create directories on QNX.

- Don’t (try to) update manifest file in “read-only” and “read-only direct”
  modes.

- Fixed a bug in caching of `stat` system calls in “file_stat_matches
  sloppiness mode”.

- Fixed bug in hashing of Clang plugins, leading to unnecessary cache misses.

- Fixed --print-config to show “pch_defines sloppiness”.

- The man page is now built when running “make install” from Git repository
  sources.


ccache 3.2.4
------------
Release date: 2015-10-08


Bug fixes
~~~~~~~~~

- Fixed build error related to zlib on systems with older make versions
  (regression in ccache 3.2.3).

- Made conversion-to-bool explicit to avoid build warnings (and potential
  runtime errors) on legacy systems.

- Improved signal handling: Kill compiler on SIGTERM; wait for compiler to exit
  before exiting; die appropriately.

- Minor fixes related to Windows support.

- The correct compression level is now used if compression is requested.

- Fixed a bug where cache cleanup could be run too early for caches larger than
  64 GiB on 32-bit systems.


ccache 3.2.3
------------
Release date: 2015-08-16


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added support for compiler option `-gsplit-dwarf`.


Bug fixes
~~~~~~~~~

- Support external zlib in nonstandard directory.

- Avoid calling `exit()` inside an exit handler.

- Let exit handler terminate properly.

- Bail out on compiler option `--save-temps` in addition to `-save-temps`.

- Only log "Disabling direct mode" once when failing to read potential include
  files.


ccache 3.2.2
------------
Release date: 2015-05-10


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added support for `CCACHE_COMPILERCHECK=string:<value>`. This is a faster
  alternative to `CCACHE_COMPILERCHECK=<command>` if the command’s output can
  be precalculated by the build system.

- Add support for caching code coverage results (compiling for gcov).


Bug fixes
~~~~~~~~~

- Made hash of cached result created with and without `CCACHE_CPP2` different.
  This makes it possible to rebuild with `CCACHE_CPP2` set without having to
  clear the cache to get new results.

- Don’t try to reset a nonexistent stats file. This avoids “No such file or
  directory” messages in the ccache log when the cache directory doesn’t exist.

- Fixed a bug where ccache deleted Clang diagnostics after compiler failures.

- Avoid performing an unnecessary copy of the object file on a cache miss.

- Bail out on too hard compiler option `-fmodules`.

- Bail out on too hard compiler option `-fplugin=libcc1plugin` (interaction
  with GDB).

- Fixed build error when compiling ccache with recent Clang versions.

- Removed signal-unsafe code from signal handler.

- Corrected logic for when to output cached stderr.

- Wipe the whole cached result on failure retrieving a cached file.

- Fixed build error when compiling ccache with recent Clang versions.


ccache 3.2.1
------------
Release date: 2014-12-10


Bug fixes
~~~~~~~~~

- Fixed regression in temporary file handling, which lead to incorrect
  permissions for stats, manifest and ccache.conf files in the cache.

- `CACHEDIR.TAG` files are now created in the [0-9a-f] subdirectories so that
  ccache.conf is not lost in backups.

- Made the default cache size suffix `G`, as previously documented.

- `-fdiagnostics-color=auto` is now passed to the compiler even if stderr is
  redirected. This fixes a problem when, for instance, a configure test probes
  if the compiler (wrapped via ccache) supports `-fdiagnostics-color=auto`.

- Added missing documentation for `max_files` and `max_size` configuration
  options.


ccache 3.2
----------
Release date: 2014-11-17


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added support for configuring ccache via one or several configuration files
  instead of via environment variables. Environment variables still have
  priority but are no longer the recommended way of customizing ccache
  behavior. See the manual for more information.

- Added support for compiler error/warning messages with color.

- Made creation of temporary directories and cache directories smarter to avoid
  unnecessary `stat` calls.

- Improved efficiency of the algorithm that scans for `__DATE_` and `__TIME__`
  tokens in the hashed source code.

- Added support for several binaries (separated by space) in `CCACHE_PREFIX`.

- The `-c` option is no longer passed to the preprocessor. This fixes problems
  with Clang and Solaris’s C++ compiler.

- ccache no longer passes preprocessor options like `-D` and `-I` to the
  compiler when compiling preprocessed output. This fixes warnings emitted by
  Clang.

- Compiler options `-fprofile-generate`, `-fprofile-arcs`, `-fprofile-use` and
  `-fbranch-probabilities` are now handled without bailing.

- Added support for Clang’s `--serialize-diagnostic` option, storing the
  diagnostic file (`.dia`) in the cache.

- Added support for precompiled headers when using Clang.

- Added support for Clang `.pth` (pretokenized header) files.

- Changed the `-x` language option to use the new objective C standard for GCC
  and Clang.

- On a cache miss, ccache now instructs the compiler to create the object file
  at the real destination and then copies the file into the cache instead of
  the other way around. This is needed to support compiler options like
  `-fprofile-arcs` and `--serialize-diagnostics`.

- ccache now checks that included files’ ctimes aren’t too new. This check can
  be turned off by adding `include_file_ctime` to the “ccache sloppiness”
  setting.

- Added possibility to get cache hits based on filename, size, mtime and ctime
  only. On other words, source code files are not even read, only stat-ed. This
  operation mode is opt-in by adding `file_stat_matches` to the “ccache
  sloppiness” setting.

- The filename part of options like `-Wp,-MDfilename` is no longer included in
  the hash since the filename doesn’t have any bearing on the result.

- Added a “read-only direct” configuration setting, which is like the ordinary
  read-only setting except that ccache will only try to retrieve results from
  the cache using the direct mode, not the preprocessor mode.

- The display and interpretation of cache size has been changed to use SI
  units.

- Default cache size is now 5 GB (was previously 1 GiB).

- Added configuration option to set the compression level of compressed object
  files in the cache.

- Added support for `@file` and `-@file` arguments (reading options from a
  file).

- `-Wl,` options are no longer included in the hash since they don’t affect
  compilation.

- Bail out on too hard compiler option `-Wp,-P`.

- Optimized MD4 calculation code on little-endian systems.

- Various improvements and fixes on win32.

- Improved logging to the ccache log file.

- Added `--dump-manifest` command-line option for debugging purposes.

- Added `--with-bundled-zlib` configure option.

- Upgraded bundled zlib to version 1.2.8.

- Improved `dev.mk` to be more platform independent.

- Made the test suite work with Clang and gcc-llvm on OS X.

- Various other improvements of the test suite.


Bug fixes
~~~~~~~~~

- Any previous `.stderr` is now removed from the cache when recaching.

- Fixed an issue when handling the `-arch` compiler option with an argument.

- Fixed race condition when creating the initial cache directory.

- Fixed test suite failures when `CC` is a ccache-wrapped compiler.


ccache 3.1.12
-------------
Release date: 2016-07-12


Bug fixes
~~~~~~~~~

- Fixed a bug where (due to ccache rewriting paths) the compiler could choose
  incorrect include files if `CCACHE_BASEDIR` is used and the source file path
  is absolute and is a symlink.


ccache 3.1.11
-------------
Release date: 2015-03-07


Bug fixes
~~~~~~~~~

- Fixed bug which could result in false cache hits when source code contains
  `'"'` followed by `" /*"` or `" //"` (with variations).

- Made hash of cached result created with and without `CCACHE_CPP2` different.
  This makes it possible to rebuild with `CCACHE_CPP2` set without having to
  clear the cache to get new results.

- Don’t try to reset a nonexistent stats file. This avoids “No such file or
  directory” messages in the ccache log when the cache directory doesn’t exist.


ccache 3.1.10
-------------
Release date: 2014-10-19


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added support for the `-Xclang` compiler option.

- Improved handling of exit code of internally executed processes.

- Zero length object files in the cache are now rejected as invalid.

- Bail out on option `-gsplit-dwarf` (since it produces multiple output files).

- Compiler option `-fdebug-prefix-map` is now ignored (not part of the hash).
  (The `-fdebug-prefix-map` option may be used in combination with
  `CCACHE_BASEDIR` to reuse results across different directories.)

- Added note in documentation that `--ccache-skip` currently does not mean
  “don’t hash the following option”.

- To enable support for precompiled headers (PCH), `CCACHE_SLOPPINESS` now also
  needs to include the new `pch_defines` sloppiness. This is because ccache
  can’t detect changes in the source code when only defined macros have been
  changed.

- Stale files in the internal temporary directory (`<ccache_dir>/tmp`) are now
  cleaned up if they are older than one hour.


Bug fixes
~~~~~~~~~

- Fixed path canonicalization in `make_relative_path()` when path doesn’t
  exist.

- Fixed bug in `common_dir_prefix_length()`. This corrects the `CCACHE_BASEDIR`
  behavior.

- ccache no longer tries to create the cache directory when `CCACHE_DISABLE` is
  set.

- Fixed bug when reading manifests with a very large number of file info
  entries.

- Fixed problem with logging of current working directory.


ccache 3.1.9
------------
Release date: 2013-01-06


Bug fixes
~~~~~~~~~

- The EAGAIN signal is now handled correctly when emitting cached stderr
  output. This fixes a problem triggered by large error outputs from the
  compiler.

- Subdirectories in the cache are no longer created in read-only mode.

- Fixed so that ccache’s log file descriptor is not made available to the
  compiler.

- Improved error reporting when failing to create temporary stdout/stderr files
  when executing the compiler.

- Disappearing temporary stdout/stderr files are now handled gracefully.


Other
~~~~~

- Fixed test suite to work on ecryptfs.


ccache 3.1.8
------------
Release date: 2012-08-11


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Made paths to dependency files relative in order to increase cache hits.

- Added work-around to make ccache work with buggy GCC 4.1 when creating a
  pre-compiled header.

- Clang plugins are now hashed to catch plugin upgrades.


Bug fixes
~~~~~~~~~

- Fixed crash when the current working directory has been removed.

- Fixed crash when stderr is closed.

- Corrected a corner case when parsing backslash escapes in string
  literals.

- Paths are now correctly canonicalized when computing paths relative to the
  base directory.


Other
~~~~~

- Made git version macro work when compiling outside of the source directory.

- Fixed `static_assert` macro definition clash with GCC 4.7.


ccache 3.1.7
------------
Release date: 2012-01-08


Bug fixes
~~~~~~~~~

- Non-writable `CCACHE_DIR` is now handled gracefully when `CCACHE_READONLY` is
  set.

- Made failure to create files (typically due to bad directory permissions) in
  the cache directory fatal. Previously, such failures were silently and
  erroneously flagged as "compiler produced stdout".

- Both the `-specs=file` and `--specs=file` forms are now recognized.

- Added recognition and hashing of GCC plugins specified with `-fplugin=file`.

- `CCACHE_COMPILERCHECK` now also determines how to hash explicit specs files
  (`-specs=file`).

- Added `CPATH`, `C_INCLUDE_PATH` and similar environment variables to the hash
  to avoid false cache hits when such variables have changed.

- Corrected log message when unify mode is enabled.

- Reverted the GCC bug compatibility introduced in ccache 3.1.5 for `-MT`/`-MQ`
  options with concatenated arguments. (The bug is fixed in recent GCC
  versions.)


Other
~~~~~

- Corrected license header for `mdfour.c`.

- Improved documentation on how to fix bad object files in the cache.



ccache 3.1.6
------------
Release date: 2011-08-21


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Rewrite argument to `--sysroot` if `CCACHE_BASEDIR` is used.


Bug fixes
~~~~~~~~~

- Don’t crash if `getcwd()` fails.

- Fixed alignment of “called for preprocessing” counter.


ccache 3.1.5
------------
Release date: 2011-05-29


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added a new statistics counter named “called for preprocessing”.

- The original command line is now logged to the file specified with
  `CCACHE_LOGFILE`.

- Improved error logging when system calls fail.

- Added support for rewriting absolute paths in `-F`/`-iframework` GCC
  options.

- Improved order of statistics counters in `ccache -s` output.


Bug fixes
~~~~~~~~~

- The `-MF`/`-MT`/`-MQ` options with concatenated argument are now handled
  correctly when they are last on the command line.

- ccache is now bug compatible with GCC for the `-MT`/`-MQ` options with
  concatenated arguments.

- Fixed a minor memory leak.

- Systems that lack (and don’t need to be linked with) libm are now supported.


ccache 3.1.4
------------
Release date: 2011-01-09


Bug fixes
~~~~~~~~~

- Made a work-around for a bug in `gzputc()` in zlib 1.2.5.

- Corrupt manifest files are now removed so that they won’t block direct mode
  hits.

- ccache now copes with file systems that don’t know about symbolic links.

- The file handle in now correctly closed on write error when trying to create
  a cache dir tag.


ccache 3.1.3
------------
Release date: 2010-11-28


Bug fixes
~~~~~~~~~

- The -MFarg, -MTarg and -MQarg compiler options (i.e, without space between
  option and argument) are now handled correctly.


Other
~~~~~

- Portability fixes for HP-UX 11.00 and other esoteric systems.


ccache 3.1.2
------------
Release date: 2010-11-21


Bug fixes
~~~~~~~~~

- Bail out on too hard compiler options `-fdump-*`.

- NULL return values from malloc/calloc of zero bytes are now handled
  correctly.

- Fixed issue when parsing precompiler output on AIX.


Other
~~~~~

- Improved documentation on which information is included in the hash sum.

- Made the “too new header file” test case work on file systems with
  unsynchronized clocks.

- The test suite now also works on systems that lack a /dev/zero.


ccache 3.1.1
------------
Release date: 2010-11-07


Bug fixes
~~~~~~~~~

- ccache now falls back to preprocessor mode when a non-regular include file
  (device, socket, etc) has been detected so that potential hanging due to
  blocking reads is avoided.

- CRC errors are now detected when decompressing compressed files in the cache.

- Fixed potential object file corruption race on NFS.

- Minor documentation corrections.

- Fixed configure detection of ar.

- ccache development version (set by dev.mk) now works with gits whose
  `describe` command doesn’t understand `--dirty`.


Other
~~~~~

- Minor debug log message improvements.


ccache 3.1
----------
Release date: 2010-09-16


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- Added support for hashing the output of a custom command (e.g. `%compiler%
  --version`) to identify the compiler instead of stat-ing or hashing the
  compiler binary. This can improve robustness when the compiler (as seen by
  ccache) actually isn’t the real compiler but another compiler wrapper.

- Added support for caching compilations that use precompiled headers. (See the
  manual for important instructions regarding this.)

- Locking of the files containing statistics counters is now done using
  symlinks instead of POSIX locks. This should make ccache behave a lot better
  on file systems where POSIX locks are slow or broken (e.g. NFS on some
  systems).

- Manifest files are now updated without the need of taking locks.

- Updates of statistics counters are now always done in one of the sub-level
  statistics files. This reduces lock contention, which especially improves
  performance on slow NFS mounts.

- Reading and writing of statistics counters has been made forward-compatible
  (unknown counters are retained).

- Files are now read without using `mmap()`. This has two benefits: it’s more
  robust against file changes during reading and it improves performance on
  poor systems where `mmap()` doesn’t use the disk cache.

- Added `.cp` and `.CP` as known C++ suffixes.

- Improved logging.

- Added `-install_name` as an option known to take an argument. (This improves
  statistics when using the Darwin linker.)


Bug fixes
~~~~~~~~~

- Non-fatal error messages are now never printed to stderr but logged instead.

- Fixed a bug affecting failing commands when `--ccache-skip` is used.

- Made `--ccache-skip` work for all options.

- EINTR is now handled correctly.


Other
~~~~~

- Work on porting ccache to win32 (native), mostly done by Ramiro Polla. The
  port is not yet finished, but will hopefully be complete in some subsequent
  release.

- Added a `--nostats` flag to the performance benchmark program.

- Made the performance benchmark program more accurate when measuring cache
  hits.

- Added a new test framework for unit tests written in C.

- Got rid of `configure-dev`; dev mode is now given by `dev.mk.in` presence.

- Improved documentation on how to combine ccache with other compiler wrappers
  (like `distcc`).

- New `LICENSE.txt` file with licensing and copyright details about bundled
  source code.

- New `AUTHORS.txt` file with a list of ccache contributors.

- New `HACKING.txt` file with some notes about ccache code conventions.


ccache 3.0.1
------------
Release date: 2010-07-15


Bug fixes
~~~~~~~~~

- The statistics counter “called for link” is now correctly updated when
  linking with a single object file.

- Fixed a problem with out-of-source builds.


ccache 3.0
----------
Release date: 2010-06-20


General
~~~~~~~

- ccache is now licensed under the GNU General Public License (GPL) version 3
  or later.


Upgrade notes
~~~~~~~~~~~~~

- The way the hashes are calculated has changed, so you won’t get cache hits
  for compilation results stored by older ccache versions. Because of this, you
  might as well clear the old cache directory with `ccache --clear` if you
  want, unless you plan to keep using an older ccache version.


New features and enhancements
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- ccache now has a “direct mode” where it computes a hash of the source code
  (including all included files) and compiler options without running the
  preprocessor. By not running the preprocessor, CPU usage is reduced; the
  speed is somewhere between 1 and 5 times that of ccache running in
  traditional mode, depending on the circumstances. The speedup will be higher
  when I/O is fast (e.g., when files are in the disk cache). The direct mode
  can be disabled by setting +CCACHE_NODIRECT+.

- Support has been added for rewriting absolute paths to relative paths when
  hashing, in order to increase cache hit rate when building the same source
  code in different directories even when compiling with `-g` and when using
  absolute include directory paths. This is done by setting the
  `CCACHE_BASEDIR` environment variable to an absolute path that specifies
  which paths to rewrite.

- Object files are now optionally stored compressed in the cache. The runtime
  cost is negligible, and more files will fit in the ccache directory and in
  the disk cache. Set `CCACHE_COMPRESS` to enable object file compression. Note
  that you can’t use compression in combination with the hard link feature.

- A `CCACHE_COMPILERCHECK` option has been added. This option tells ccache what
  compiler-identifying information to hash to ensure that results retrieved
  from the cache are accurate. Possible values are: none (don’t hash anything),
  mtime (hash the compiler’s mtime and size) and content (hash the content of
  the compiler binary). The default is mtime.

- It is now possible to specify extra files whose contents should be included
  in the hash sum by setting the `CCACHE_EXTRAFILES` option.

- Added support for Objective-C and Objective-C\+\+. The statistics counter
  “not a C/C++ file” has been renamed to “unsupported source language”.

- Added support for the `-x` compiler option.

- Added support for long command-line options.

- A `CACHEDIR.TAG` file is now created in the cache directory. See
  <http://www.brynosaurus.com/cachedir/>.

- Messages printed to the debug log (specified by `CCACHE_LOGFILE`) have been
  improved.

- You can relax some checks that ccache does in direct mode by setting
  `CCACHE_SLOPPINESS`. See the manual for more information.

- `CCACHE_TEMPDIR` no longer needs to be on the same filesystem as
  `CCACHE_DIR`.

- The default value of `CCACHE_TEMPDIR` has been changed to `$CCACHE_DIR/tmp`
  to avoid cluttering the top directory.

- Temporary files that later will be moved into the cache are now created in
  the cache directory they will end up in. This makes ccache more friendly to
  Linux’s directory layout.

- Improved the test suite and added tests for most of the new functionality.
  It’s now also possible to specify a subset of tests to run.

- Standard error output from the compiler is now only stored in the cache if
  it’s non-empty.

- If the compiler produces no object file or an empty object file, but gives a
  zero exit status (could be due to a file system problem, a buggy program
  specified by `CCACHE_PREFIX`, etc.), ccache copes with it properly.

- Added `installcheck` and `distcheck` make targets.

- Clarified cache size limit options’ and cleanup semantics.

- Improved display of cache max size values.

- The following options are no longer hashed in the preprocessor mode:
  `-imacros`, `-imultilib`, `-iprefix`, `-iquote`, `-isysroot`, `-iwithprefix`,
  `-iwithprefixbefore`, `-nostdinc`, `-nostdinc++` and `-U`.


Bug fixes
~~~~~~~~~

- Various portability improvements.

- Improved detection of home directory.

- User-defined `CPPFLAGS` and `LDFLAGS` are now respected in the Makefile.

- Fixed NFS issues.

- Computation of the hash sum has been improved to decrease the risk of hash
  collisions. For instance, the compiler options `-X -Y` and `-X-Y` previously
  contributed equally to the hash sum.

- Bail out on too hard compiler options `--coverage`, `-fprofile-arcs`,
  `-fprofile-generate`, `-fprofile-use`, `-frepo`, `-ftest-coverage` and
  `-save-temps`. Also bail out on `@file` style options.

- Errors when using multiple `-arch` compiler options are now noted as
  “unsupported compiler option”.

- `-MD`/`-MMD` options without `-MT`/`-MF` are now handled correctly.

- The `-finput-charset` option is now handled correctly.

- Added support for `-Wp,-MD` and `-Wp,-MMD` options.

- The compiler options `-Xassembler`, `-b`, `-G` and `-V` are now correctly
  recognized as taking an argument.

- Debug information containing line numbers of predefined and command-line
  macros (enabled with the compiler option `-g3`) will now be correct.

- Corrected LRU cleanup handling of object files.

- `utimes()` is now used instead of `utime()` when available.

- Non-writable cache directories are now handled gracefully.

- Corrected documentation about sharing the cache directory.

- Fixed compilation warnings from GCC 4.3.

- The command specified by `CCACHE_PREFIX` is no longer part of the hash.

- Fixed bad memory access spotted by Valgrind.

- Fixed a bug in `x_realloc`.

- Freed memory is no longer referenced when compiling a `.i`/`.ii` file and
  falling back to running the real compiler.

- The test suite is now immune to external values of the `CCACHE_*` environment
  variables.

- Improved detection of recursive invocation.

- The ccache binary is now not unconditionally stripped when installing.

- Statistics counters are now correctly updated for -E option failures and
  internal errors.
