FROM fedora:32

RUN dnf install -y \
        autoconf \
        bash \
        ccache \
        clang \
        cmake \
        diffutils \
        elfutils \
        findutils \
        gcc \
        gcc-c++ \
        libzstd-devel \
        make \
 && dnf clean all
