#!/bin/sh

set -eu

rm -rf build_package_source_dir_test
mkdir -p build_package_source_dir_test
cd build_package_source_dir_test
cmake ..
cmake --build . --target package_source

tmp_dir=$(mktemp -d)
trap "rm -rf $tmp_dir" EXIT

tar -xf ccache-*.tar.xz -C $tmp_dir
cd $tmp_dir/ccache-*

cmake .
cmake --build . -- -j4
ctest --output-on-failure -j4
