#!/bin/sh

set -eux

build() {
    mkdir -p "build_$1"
    cd "build_$1"
    cmake \
        -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_OSX_DEPLOYMENT_TARGET="10.15" \
        -D CMAKE_OSX_ARCHITECTURES="$1" \
        -D CMAKE_SYSTEM_PROCESSOR="$1" \
        -D DEPS=DOWNLOAD \
        -D ENABLE_TESTING=OFF \
        ..
    cmake --build .
    cd ..
}

FILES=""
set -- x86_64 arm64

for i in "$@"; do
    echo "Building $i"
    build "$i"
    FILES="${FILES} build_$i/ccache"
done

mkdir -p install/bin
lipo -create $FILES -output install/bin/ccache
lipo -info install/bin/ccache

find install -ls
