#!/bin/sh

set -eu

rm -rf build_package_dir_test
mkdir -p build_package_dir_test
cd build_package_dir_test
cmake ..
cmake --build . --target package

# Get out of git directory just to be sure.
tmp_dir=$(mktemp -d)
trap "rm -rf $tmp_dir" EXIT

tar -xf ccache-*.tar.xz -C $tmp_dir

CCACHE=$(echo $tmp_dir/ccache-*/bin/ccache) ../test/run
