#!/bin/sh

set -eu

rm -rf build_package_source_dir_test
mkdir -p build_package_source_dir_test
cd build_package_source_dir_test
cmake ..
cmake --build . --target package_source

# get out of git directory
# Unfortunately this random name will prevent ccache from caching results...
# TODO: use '../../temp' instead?
tmp_dir=$(mktemp -d)
trap "rm -rf $tmp_dir" EXIT

tar -xf ccache-src.tar.gz -C $tmp_dir
cd $tmp_dir/ccache-src

cmake .
cmake --build . -- -j4
ctest --output-on-failure -j4

echo "Source package is fine and can be used."

