#!/bin/sh

set -eu

rm -rf build_package_dir_test
mkdir -p build_package_dir_test
cd build_package_dir_test
cmake ..
cmake --build . --target package

# get out of git directory just to be sure
tmp_dir=$(mktemp -d)
trap "rm -rf $tmp_dir" EXIT

tar -xzf ccache-binary.tar.gz -C $tmp_dir

CCACHE=$tmp_dir/ccache-binary/bin/ccache ../test/run

echo "Binary package is fine and can be used."
