#!/bin/bash

set -euo pipefail

asciidoctor=$1
pandoc=$2
stylesheet=$3
version=$4
input=$5
output=$6

"${asciidoctor}" \
  -a revnumber="${version}" \
  -a icons=font \
  -a toc=left \
  -a sectanchors \
  -a stylesheet="${stylesheet}" \
  -b html \
  -o "${output}" \
  "${input}"
